/* Builds the CSS bundles served to the browser (v16).

   The site grew as twelve layered stylesheets (v6 → v15). Each page used to
   request 9–12 of them as separate render-blocking files. This script
   concatenates them in exactly the original cascade order, so rendering is
   identical, and applies a conservative minification (comments and
   insignificant whitespace only).

   Edit the source files in assets/, then run:  npm run build:css
   Verify bundles are current (used by tests):   npm run build:css -- --check */
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const assets = path.join(root, 'assets');

export const BUNDLES = {
  // index, product and my-pages (storefront pages using the v6–v10 catalogue layers)
  'bundle-storefront.css': ['styles.css', 'v7.css', 'v8.css', 'v8-1.css', 'v9.css', 'v10.css', 'v11.css', 'v12.css', 'v12-7.css', 'v12-9-mobile.css', 'v13-mobile-commerce.css', 'v15-premium.css'],
  // guide, Ask Vera, checkout, order tracking, legal pages and 404
  'bundle-pages.css': ['styles.css', 'v8-1.css', 'v9.css', 'v11.css', 'v12.css', 'v12-7.css', 'v12-9-mobile.css', 'v13-mobile-commerce.css', 'v15-premium.css'],
  // administration
  'bundle-admin.css': ['styles.css', 'v8.css', 'v8-1.css', 'v9.css', 'v11.css', 'v12.css', 'v12-7.css', 'v12-9-mobile.css', 'v13-mobile-commerce.css', 'v14-production-readiness.css', 'v15-premium.css']
};

/* Removes comments and collapses whitespace outside of strings and url(). */
export function minifyCss(css) {
  let out = '';
  let i = 0;
  const n = css.length;
  while (i < n) {
    const ch = css[i];
    if (ch === '/' && css[i + 1] === '*') {
      const end = css.indexOf('*/', i + 2);
      i = end === -1 ? n : end + 2;
      continue;
    }
    if (ch === '"' || ch === "'") {
      let j = i + 1;
      while (j < n && css[j] !== ch) j += css[j] === '\\' ? 2 : 1;
      out += css.slice(i, j + 1);
      i = j + 1;
      continue;
    }
    if (/\s/.test(ch)) {
      while (i < n && /\s/.test(css[i])) i++;
      const prev = out[out.length - 1];
      const next = css[i];
      if (prev && next && !'{};,>'.includes(prev) && !'{};,>'.includes(next)) out += ' ';
      continue;
    }
    out += ch;
    i++;
  }
  return out.replace(/;}/g, '}').trim();
}

export function buildBundle(name) {
  const header = `/* ${name} — generated by scripts/build-css.mjs from: ${BUNDLES[name].join(', ')}. Do not edit directly. */\n`;
  return header + BUNDLES[name].map(file => {
    const source = fs.readFileSync(path.join(assets, file), 'utf8');
    return `/* ${file} */\n${minifyCss(source)}`;
  }).join('\n') + '\n';
}

const isMain = process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url);
if (isMain) {
  const check = process.argv.includes('--check');
  let stale = 0;
  for (const name of Object.keys(BUNDLES)) {
    const target = path.join(assets, name);
    const built = buildBundle(name);
    if (check) {
      const current = fs.existsSync(target) ? fs.readFileSync(target, 'utf8') : '';
      if (current !== built) { stale++; console.error(`${name} is out of date. Run: npm run build:css`); }
    } else {
      fs.writeFileSync(target, built);
      const raw = BUNDLES[name].reduce((sum, file) => sum + fs.statSync(path.join(assets, file)).size, 0);
      console.log(`${name}: ${BUNDLES[name].length} files, ${(raw / 1024).toFixed(0)} KB → ${(built.length / 1024).toFixed(0)} KB`);
    }
  }
  if (check) { if (stale) process.exit(1); console.log('CSS bundles are up to date.'); }
}
